name: Deploy to Railway

on:
  push:
    paths:
      - 'main.py'
      - 'response.py'
      - 'view/**'
      - 'app/**'
      - 'assets/**'
      - '.github/workflows/main.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: my-service-id
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ secrets.SVC_ID }}
